### ISSUE TITLE
Make hidden page to manually sync tempos

### ISSUE THREAD

**Issue by WolfBerwouts** [opengridcc/website#30]

**Comment by JrtPec** [comment]
Perhaps we could make an admin login, we could use https://github.com/singingwolfboy/flask-dance and login with our github accounts.
This solution uses a database to store user info, so it could also be a way to introduce SQLAlchemy into the website (opengridcc/opengrid#91)

Edit: I have made a separate issue (#40) because admin sign in is a larger issue while a secret page is actually fairly straightforward.

**Comment by JrtPec** [comment]
implemented in #44
